info/__init__.py
from flask import Flask
# 导入Config类，导入config_dict字典
from config import Config,config_dict
# 导入flask_session扩展包，用来指定session信息存储的位置
from flask_session import Session
# 导入flask_sqlalchemy扩展，实现数据库的连接
from flask_sqlalchemy import SQLAlchemy
# 导入标准模块
import logging
from logging.handlers import RotatingFileHandler

# 设置日志的记录等级
logging.basicConfig(level=logging.DEBUG) # 调试debug级
# 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024*1024*100, backupCount=10)
# 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
# 为刚创建的日志记录器设置日志记录格式
file_log_handler.setFormatter(formatter)
# 为全局的日志工具对象（flask app使用的）添加日志记录器
logging.getLogger().addHandler(file_log_handler)
# 实例化redis对象
from redis import StrictRedis

redis_store = StrictRedis(host=Config.REDIS_HOST,port=Config.REDIS_PORT,decode_responses=True)

# 先实例化sqlalchemy对象
db = SQLAlchemy()
# 导入flask_wtf扩展提供的csrf保护功能
from flask_wtf import CSRFProtect,csrf

# 定义工厂函数，让函数根据参数的不同，生产不同环境下的app，即开发模式下的app，或生产模式下的app
def create_app(config_name):

    app = Flask(__name__)
    app.config.from_object(config_dict[config_name])
    # 让sqlalchemy对象通过函数调用，实现和程序实例app进行关联
    db.init_app(app)
    Session(app)
    # 后端服务器开启csrf保护,不仅会验证请求方法POST/PUT/DELETE/PATCH/，
    # 还会验证请求头中是否设置了X-CSRFToken
    # csrf_token = 'asdfasdfas'
    CSRFProtect(app)

    # 生成csrf_token
    # respose = make_response()
    # response.set_cookie('csrf_token',csrf_token)
    @app.after_request
    def after_request(response):
        csrf_token = csrf.generate_csrf()
        # 把csrf_token设置到客户端浏览器的cookie中
        response.set_cookie('csrf_token', csrf_token)
        return response
        # 使用自定义的过滤器

    from info.utils.commons import index_filter
    app.add_template_filter(index_filter, 'index_filter')

    # 导入蓝图对象，注册蓝图对象
    from info.modules.news import news_blue
    app.register_blueprint(news_blue)
    from info.modules.passport import passport_blue
    app.register_blueprint(passport_blue)
    from info.modules.profile import profile_blue
    app.register_blueprint(profile_blue)

    return app

info/modules/news/__init__.py
from flask import Blueprint


# 创建新闻模块的蓝图对象

news_blue = Blueprint('news_blue',__name__)

# 把使用蓝图对象的文件，导入到创建蓝图对象的下面
from . import views

info/modules/news/views.py
# 导入蓝图对象
from flask import session, render_template, current_app, jsonify, request, g
# 导入模型类
from info import db, constants
from info.models import User, News, Category
# 导入自定义的状态码
from info.utils.response_code import RET
from . import news_blue
# 导入自定义的登录验证装饰器
from info.utils.commons import login_required


# 首页模板数据加载
@news_blue.route('/')
@login_required
def index():
    user = g.user

    # 新闻分类数据展示
    try:
        categories = Category.query.all()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询分类数据异常')
    # 判断查询结果
    if not categories:
        return jsonify(errno=RET.NODATA, errmsg='无分类数据')
    # # 定义容器存储查询结果
    # category_list = []
    # # 遍历查询结果
    # for category in categories:
    #     category_list.append(category.to_dict())

    # 新闻点击排行
    # 默认按照新闻的点击次数倒序排序
    # 获取点击排行数据
    news_list = []
    try:
        news_list = News.query.order_by(News.clicks.desc()).limit(6)
        # news_list = News.query.filter().order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS).all()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询新闻数据异常')
    # 判断查询结果是否存在
    if not news_list:
        return jsonify(errno=RET.NODATA, errmsg='无新闻数据')

    # 返回数据
    data = {
        'user_info': user.to_dict() if user else None,
        'news_click_list': [news.to_dict() for news in news_list],
        'category_list': [category.to_dict() for category in categories]
    }

    return render_template('news/index.html', data=data)


# 项目favicon.ico文件的加载
@news_blue.route('/favicon.ico')
def favicon():
    """
    http://127.0.0.1:5000/favicon.ico
    实现/favicon.ico路径下的图标加载
    1、favicon图标的加载，不是每次请求都加载，是浏览器默认实现的，如果有缓存，必须要清除缓存，
    2、把浏览器彻底关闭，重启浏览器。
    :return:
    """
    # 使用current_app调用flask内置的函数，发送静态文件给浏览器，实现logo图标的加载
    return current_app.send_static_file('news/favicon.ico')


@news_blue.route('/news_list')
def get_news_list():
    """
    新闻列表
    1、获取参数，cid，page，per_page
    2、检查参数的类型
    3、根据cid来查询mysql数据库,最新
    如果用户选择的是最新，默认查询所有新闻数据
    News.query.filter().order_by(News.create_time.desc()).paginate(page,per_page,False)
    News.query.filter(News.category_id==cid).order_by(News.create_time.desc()).paginate(page,per_page,False)
    4、获取分页后的数据
    总页数、当前页数、新闻列表
    5、返回结果
    :return:
    """
    # 获取参数
    cid = request.args.get('cid', '1')
    page = request.args.get('page', '1')
    per_page = request.args.get('per_page', '10')
    # 转换参数的数据类型
    try:
        cid, page, per_page = int(cid), int(page), int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg='参数格式错误')
    # 定义容器，存储查询的过滤条件
    filters = []
    # 判断分类id如果不是最新
    if cid > 1:
        filters.append(News.category_id == cid)
    # 使用过滤条件查询mysql，按照新闻发布时间排序
    # print(filters)
    try:
        # *filters表示python中拆包，News.category_id==cid，*filters里面存储的是sqlalchemy对象
        # 在python中测试添加的数据为True或False
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询新闻数据失败')
    # 获取分页后的数据
    news_list = paginate.items
    total_page = paginate.pages
    current_page = paginate.page
    # 定义容器，存储查询到的新闻数据
    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_dict())
    data = {
        'news_dict_list': news_dict_list,
        'total_page': total_page,
        'current_page': current_page
    }
    # 返回数据
    return jsonify(errno=RET.OK, errmsg='OK', data=data)


@news_blue.route('/<int:news_id>')
@login_required
def get_news_detail(news_id):
    """
    新闻详情
        用户数据展示
        点击排行展示
        新闻数据展示
    :param news_id:
    :return:
    """
    # 从登录验证装饰器中获取用户信息
    user = g.user
    # 新闻点击排行
    try:
        news_list = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询新闻排行数据失败')
    if not news_list:
        return jsonify(errno=RET.NODATA, errmsg='无新闻排行数据')
    news_click_list = []
    for news in news_list:
        news_click_list.append(news.to_dict())

    # 新闻详情数据
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询新闻详情数据失败')
    if not news:
        return jsonify(errno=RET.NODATA, errmsg='无新闻详情数据')
    # 收藏或取消收藏的标记
    is_collected = False
    # 判断用户是否收藏过,用户登录后才能显示该新闻是否收藏
    if user:
        if news in user.collection_news:
            is_collected = True
    data = {
        'user_info': user.to_dict() if user else None,
        'news_click_list': news_click_list,
        'news_detail': news.to_dict(),
        'is_collected': is_collected
    }

    return render_template('news/detail.html', data=data)


@news_blue.route("/news_collect",methods=['POST'])
@login_required
def news_collect():
    """
    新闻收藏和取消收藏
    1、获取参数，news_id,action[collect,cancel_collect]
    2、检查参数的完整性
    3、转换news_id参数的数据类型
    4、检查action参数的范围
    5、查询mysql确认新闻的存在
    6、校验查询结果
    7、判断用户选择的是收藏，还要判断用户之前未收藏过
    user.collection_news.append(news)
    如果是取消收藏
    user.collection_news.remove(news)
    8、提交数据mysql
    9、返回结果


    :return:
    """
    # 从登录验证装饰器中获取用户信息
    user = g.user
    # 判断用户是否登录
    if not user:
        return jsonify(errno=RET.SESSIONERR,errmsg='用户未登录')

    news_id = request.json.get('news_id')
    action = request.json.get('action')
    # 检查参数的完整性
    if not all([news_id,action]):
        return jsonify(errno=RET.PARAMERR,errmsg='参数不完整')
    # 转换newsid数据类型
    try:
        news_id = int(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR,errmsg='参数类型错误')
    # 检查action参数的范围
    if action not in ['collect','cancel_collect']:
        return jsonify(errno=RET.PARAMERR,errmsg='参数范围错误')
    # 根据新闻id查询数据
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg='查询数据失败')
    # 判断查询结果
    if not news:
        return jsonify(errno=RET.NODATA,errmsg='无新闻数据')
    # 如果用户选择的是收藏
    if action == 'collect':
        # 该新闻用户之前未收藏
        if news not in user.collection_news:
            user.collection_news.append(news)
    else:
        user.collection_news.remove(news)
    # 提交数据
    try:
        db.session.add(user)
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR,errmsg='保存数据失败')
    # 返回结果
    return jsonify(errno=RET.OK,errmsg='OK')

info/modules/passport/__init__.py
from flask import Blueprint

passport_blue = Blueprint('passport_blue',__name__)


from . import views

info/modules/profile/__init__.py
from flask import Blueprint

profile_blue = Blueprint('profile_blue', __name__, url_prefix='/user')

# RESTful：表现层状态转换，开发web项目需要具备的风格特点。
from . import views

info/modules/profile/views.py
from flask import g, redirect, render_template, request, jsonify, current_app, session
import uuid
from . import profile_blue
from info.utils.commons import login_required
from info.utils.response_code import RET
from info import db, constants
# 导入阿里云
from info.utils.image_storage import storage
# 导入模型类
from info.models import Category, News


@profile_blue.route("/info")
@login_required
def user_info():
    """
    个人中心基本资料展示
    1、尝试获取用户信息
    # user = g.user
    2、如果用户未登录，重定向到项目首页
    3、如果用户登录，获取用户信息
    4、把用户信息传给模板
    :return:
    """
    user = g.user
    if not user:
        return redirect('/')
    data = {
        'user_info': user.to_dict()
    }
    return render_template('news/user.html', data=data)


@profile_blue.route("/base_info", methods=['GET', 'POST'])
@login_required
def base_info():
    """
    基本资料的展示和修改
    1、尝试获取用户信息
    2、如果是get请求，返回用户信息给模板
    如果是post请求：
    1、获取参数，nick_name,signature,gender[MAN,WOMAN]
    2、检查参数的完整性
    3、检查gender性别必须在范围内
    4、保存用户信息
    5、提交数据
    6、修改redis缓存中的nick_name
    注册：session['nick_name'] = mobile
    登录：session['nick_name'] = user.nick_name
    修改：session['nick_name'] = nick_name

    7、返回结果


    :return:
    """
    user = g.user
    if request.method == 'GET':
        data = {
            'user': user.to_dict()
        }
        return render_template('news/user_base_info.html', data=data)
    # 获取参数
    nick_name = request.json.get('nick_name')
    signature = request.json.get('signature')
    gender = request.json.get('gender')
    # 检查参数
    if not all([nick_name, signature, gender]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数缺失')
    # 校验性别参数范围
    if gender not in ['MAN', 'WOMAN']:
        return jsonify(errno=RET.PARAMERR, errmsg='参数范围错误')
    # 保存用户信息
    user.nick_name = nick_name
    user.signature = signature
    user.gender = gender
    # 提交数据
    try:
        db.session.add(user)
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg='保存数据失败')
    # 修改redis缓存中的用户信息
    session['nick_name'] = nick_name
    # 返回结果
    return jsonify(errno=RET.OK, errmsg='OK')


@profile_blue.route("/pic_info", methods=['GET', 'POST'])
@login_required
def save_avatar():
    """
    保存用户头像
    获取用户信息，如果是get请求，user.to_dict()加载模板
    1、获取参数，
    avatar = request.files.get('avatar')
    文件对象：具有读写方法的对象
    2、检查参数
    3、读取文件对象
    4、调用阿里云，上传头像
    5、保存用户头像数据，提交到mysql中是图片名称
    6、拼接图片的完整的绝对路径
    外链域名+图片名称：http://p8m0n4bb5.bkt.clouddn.com/图片名称
    7、返回结果

    :return:
    """
    user = g.user
    if request.method == 'GET':
        data = {
            'user': user.to_dict()
        }
        return render_template('news/user_pic_info.html', data=data)
    # 获取文件参数
    avatar = request.files.get('avatar')
    # 检查参数
    if not avatar:
        return jsonify(errno=RET.PARAMERR, errmsg='参数错误')
    # # 读取图片数据，转换成bytes类型

    try:
        file_name = str(uuid.uuid1()) + "_" + avatar.filename
        image_name = storage(avatar.read(), file_name)
        # print(image_name)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.THIRDERR, errmsg='上传图片失败')
    # 保存图片文件的名称到mysql数据库中
    user.avatar_url = image_name
    # 提交数据
    try:
        db.session.add(user)
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg='保存数据失败')
    # 拼接图片的绝对路径，返回前端
    avatar_url = constants.IMG_DOMIN_PREFIX + image_name
    data = {
        'avatar_url': avatar_url
    }
    # 返回数据
    return jsonify(errno=RET.OK, errmsg='OK', data=data)


@profile_blue.route('/news_release', methods=['GET', 'POST'])
@login_required
def news_release():
    """
    新闻发布：
    如果是get请求，加载新闻分类，需要移除'最新'分类，传给模板
    :return:
    """
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg='用户未登录')

    if request.method == 'GET':
        try:
            category_list = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg='查询新闻分类数据失败')
        # 判断查询结果
        if not category_list:
            return jsonify(errno=RET.NODATA, errmsg='无新闻分类数据')
        categories = []
        for category in category_list:
            categories.append(category.to_dict())
        # 移除最新
        categories.pop(0)
        data = {
            'categories': categories
        }
        return render_template('news/user_news_release.html', data=data)
    else:
        # 如果不是get请求，获取参数,title,category_id,digest,index_image,content
        title = request.form.get('title')
        category_id = request.form.get('category_id')
        digest = request.form.get('digest')
        content = request.form.get('content')
        index_image = request.files.get('index_image')
        # 检查参数的完整性
        if not all([title, category_id, digest,index_image,content]):
            return jsonify(errno=RET.PARAMERR, errmsg='参数缺失')
        # 转换新闻分类数据类型
        try:
            category_id = int(category_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.PARAMERR, errmsg='参数类型错误')
        # 读取图片数据
        try:
            image_data = index_image.read()
            imgname = "IMG" + str(uuid.uuid1()) + "_" + index_image.filename
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.PARAMERR, errmsg='参数格式错误')

        try:
            image_name = storage(image_data, imgname)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.THIRDERR, errmsg='上传图片失败')
        # 保存新闻数据
        news = News()
        news.category_id = category_id
        news.user_id = user.id
        news.source = '个人发布'
        news.title = title
        news.digest = digest

        # news.index_image_url = index_image
        # 新闻图片应该存储的是图片的绝对路径,让新闻图片和新闻内容是一个整体。
        news.index_image_url = constants.IMG_DOMIN_PREFIX + image_name
        news.content = content
        news.status = 1
        # 提交数据
        try:
            db.session.add(news)
            db.session.commit()
        except Exception as e:
            current_app.logger.error(e)
            db.session.rollback()
            return jsonify(errno=RET.DBERR, errmsg='保存数据失败')
        # 返回结果
        return jsonify(errno=RET.OK, errmsg='OK')


@profile_blue.route('/news_list')
@login_required
def news_list():
    # 获取页数
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except Exception as e:
        current_app.logger.error(e)
        p = 1

    user = g.user
    news_li = []
    current_page = 1
    total_page = 1
    try:
        paginate = News.query.filter(News.user_id == user.id).paginate(p, constants.USER_COLLECTION_MAX_NEWS, False)
        # 获取当前页数据
        news_li = paginate.items
        # 获取当前页
        current_page = paginate.page
        # 获取总页数
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_li = []

    for news_item in news_li:
        news_dict_li.append(news_item.to_review_dict())
    data = {"news_list": news_dict_li, "total_page": total_page, "current_page": current_page}
    return render_template('news/user_news_list.html', data=data)

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}新经资讯网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>

    {% block scriptBlock %}{% endblock %}
</head>
<body>
<div class="header_con">
    <div class="header">
        <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
        {% block headerBlock %}

        {% endblock %}
        {% if data.user_info %}
            <!-- 用户登录后显示下面，隐藏上面 -->
            <div class="user_login fr">
                <img src="{% if data.user_info.avatar_url %}{{ data.user_info.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}"
                     class="lgin_pic">
                <a href="/user/info">{{ data.user_info.nick_name }}</a>
                <a href="javascript:;" onclick="logout()">退出</a>
            </div>
        {% else %}
            <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>
        {% endif %}
    </div>
</div>

<div class="conter_con">
    {% block contentBlock %}

    {% endblock %}

    {% block rankBlock %}
        <div class="rank_con fr">
            {% block authorBlock %}
            {% endblock %}
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">

                {% for news in data.news_click_list %}
                    <li><span class="{{ loop.index | index_filter }}">{{ loop.index }}</span><a
                            href="/{{ news.id }}">{{ news.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endblock %}
</div>
<div class="footer">
    <div class="footer_links">
        <a href="">关于我们</a>
        <span>|</span>
        <a href="">联系我们</a>
        <span>|</span>
        <a href="">招聘人才</a>
        <span>|</span>
        <a href="">友情链接</a>
    </div>
    <p class="copyright">
        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>
        电话：010-****888 京ICP备*******8号
    </p>
</div>

<!-- 登录表单 -->
<form class="login_form_con">
    <div class="login_form">
        <div class="login_title">
            <h3>登 录</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <!--<div class="form_group">-->
        <!--<input id="mobile" type="text" name="mobile" autocomplete="off">-->
        <!--<div class="input_tip">手机号</div>-->
        <!--<div id="login-mobile-err" class="error_tip">手机号不能为空</div>-->
        <!--</div>-->
        <div class="form_group">
            <input id="email" type="text" name="email" autocomplete="off">
            <div class="input_tip">邮箱</div>
            <div id="login-email-err" class="error_tip">邮箱不能为空</div>
        </div>
        <div class="form_group">
            <input id="password" type="password" name="password">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="login-password-err" class="error_tip">密码不能为空</div>
        </div>
        <input type="submit" name="" value="登 录" class="input_sub">
        <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
    </div>
    <div class="mask"></div>
</form>

<!-- 注册表单 -->
<form class="register_form_con">
    <div class="register_form">
        <div class="register_title">
            <h3>注 册</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <!--<div class="form_group">-->
        <!--<input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">-->
        <!--<div class="input_tip">手机号</div>-->
        <!--<div id="register-mobile-err" class="error_tip">手机号不能为空</div>-->
        <!--</div>-->
        <div class="form_group">
            <input type="text" name="email" autocomplete="off" id="register_email" class="mail_input">
            <div class="input_tip">邮箱</div>
            <div id="register-email-err" class="error_tip">邮箱不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
            <div class="input_tip">图形验证码</div>
            <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
            <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="smscode" id="smscode" class="code_pwd">
            <div class="input_tip">验证码</div>
            <a href="javascript:;" class="get_code" onclick="sendEmail()">点击获取验证码</a>
            <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
        </div>
        <div class="form_group">
            <input type="password" name="password" id="register_password" class="pass_input">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="register-password-err" class="error_tip">密码不能为空</div>
        </div>
        <div class="form_group2 clearfix">
            <input type="checkbox" class="agree_input" checked>
            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
            <div class="error_tip">请勾选</div>
        </div>
        <input type="submit" name="" value="注 册" class="input_sub">
        <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
    </div>
    <div class="mask"></div>
</form>
</body>
</html>

info/templates/news/index.html
{% extends 'news/base.html' %}

{% block titleBlock %}
    首页-新经资讯
{% endblock %}

{% block scriptBlock %}
    <script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}

{% block headerBlock %}
    <ul class="menu fl">
        {% for category in data.category_list %}
            <li class="{% if loop.index0 == 0 %}active{% endif %}" data-cid="{{ category.id }}"><a
                    href="javascript:;">{{ category.name }}</a></li>

        {% endfor %}
    </ul>
{% endblock %}

{% block contentBlock %}
    <ul class="list_con fl">
    </ul>
{% endblock %}

info/templates/news/user.html
{% extends "news/base.html" %}

{% block titleBlock %}
    用户中心
{% endblock %}

{% block contentBlock %}
    <div class="user_menu_con fl">
        <div class="user_center_pic">
            <img src={% if data.user_info.avatar_url %}
                {{ data.user_info.avatar_url }}
            {% else %}
                "../../static/news/images/user_pic.png"
            {% endif %} alt="用户图片">
        </div>
        <div class="user_center_name">{{ data.user_info.nick_name }}</div>


        <ul class="option_list">
            <li class="active"><a href="{{ url_for("profile_blue.base_info") }}" target="main_frame">基本资料</a></li>
            <li><a href="/user/pic_info" target="main_frame">头像设置</a></li>
            <li><a href="/user/user_follow" target="main_frame">我的关注</a></li>
            <li><a href="/user/pass_info" target="main_frame">密码修改</a></li>
            <li><a href="/user/collection" target="main_frame">我的收藏</a></li>
            <li><a href="/user/news_release" target="main_frame">新闻发布</a></li>
            <li><a href="/user/news_list" target="main_frame">新闻列表</a></li>
        </ul>
    </div>

    <div class="user_con fr">
        <iframe src="{{ url_for("profile_blue.base_info") }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
    </div>
{% endblock %}

{% block rankBlock %}
    {#重写rankBlock，内部什么什么都不填#}
{% endblock %}

info/templates/news/user_base_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/user_base_info.js"></script>
</head>
<body class="inframe_body">
<form class="base_info">
    <h3>基本资料</h3>
    <div class="form-group">
        <label>个性签名：</label>
        <input type="text" id="signature" name="signature" class="input_txt" value="{{ data.user.signature }}">
    </div>
    <div class="form-group">
        <label>用户昵称：</label>
        <input type="text" id="nick_name" name="nick_name" class="input_txt" value="{{ data.user.nick_name }}">
    </div>
    <div class="form-group">
        <label>性别：</label>
        {% if data.user.gender == "MAN" %}
            <input class="gender" type="radio" name="gender" checked="checked" value="MAN"> <b>男</b>
            <input class="gender" type="radio" name="gender" value="WOMAN">  <b>女</b>
        {% else %}
            <input class="gender" type="radio" name="gender" value="MAN"> <b>男</b>&nbsp;&nbsp;&nbsp;
            <input class="gender" type="radio" name="gender" value="WOMAN" checked="checked">  <b>女</b>
        {% endif %}
    </div>
    <div class="form-group">
        <input type="submit" value="保 存" class="input_sub">
    </div>
</form>

</body>
</html>